export const collections = [
  {
    slug: "timeless-gold",
    name: "Timeless Gold",
    tagline: "Solid warmth for everyday reverence",
    description: "Sculptural 18-karat gold forms selected for daily ritual.",
    featured: true,
  },
  {
    slug: "the-pearl-edit",
    name: "The Pearl Edit",
    tagline: "Unregulated organic luster",
    description: "Freshwater and baroque pearls with a quiet, modern point of view.",
    featured: true,
  },
  {
    slug: "silver-moon",
    name: "Silver Moon",
    tagline: "Satin textures under pale light",
    description: "Cool sterling silver pieces with a satin-brushed finish.",
    featured: true,
  },
  {
    slug: "atelier-heritage",
    name: "Heritage Edit",
    tagline: "Ceremonial weight without convention",
    description: "Timeless silhouettes selected from the Thumba archive.",
    featured: true,
  },
] as const;

export const products = [
  {
    slug: "nila-pearl-necklace",
    name: "Nila Pearl Necklace",
    subtitle: "Lustrous freshwater pearls on an 18k gold clasp",
    description: "A quiet strand of freshwater pearls with natural surface character and soft luminescence.",
    story: "Inspired by the evening tides of Kerala's backwaters.",
    price: 14800,
    discountedPrice: 12800,
    category: "necklaces",
    careInstructions: "Wipe clean with a soft microfiber cloth after wear. Store away from direct sunlight and perfumes.",
    collectionSlug: "the-pearl-edit",
    featured: true,
    isNew: false,
    details: ["Silk-cord construction", "Signature hallmarked clasp", "Delivered in a suede keepsake box"],
  },
  {
    slug: "aruna-sculpted-hoops",
    name: "Aruna Sculpted Hoops",
    subtitle: "Fluid tapered hoops with a satin-brushed luster",
    description: "A featherlight organic hoop that contours the jawline with subtle architectural presence.",
    story: "Chosen to catch morning light with gentle diffusion.",
    price: 6800,
    discountedPrice: 5400,
    category: "earrings",
    collectionSlug: "timeless-gold",
    featured: true,
    isNew: false,
    details: ["Featherlight hollow construction", "Secure hinged clasp", "Nickel-free"],
  },
  {
    slug: "chandra-signet-ring",
    name: "Chandra Signet Ring",
    subtitle: "A satin-finished signet with an heirloom profile",
    description: "A substantial everyday signet ring with a softly faceted face and quiet, tactile polish.",
    price: 9200,
    category: "rings",
    collectionSlug: "silver-moon",
    featured: true,
    isNew: true,
    details: ["Satin-brushed surface", "Hallmarked sterling silver"],
  },
  {
    slug: "neelam-chain-bracelet",
    name: "Neelam Chain Bracelet",
    subtitle: "An architectural curb chain in warm yellow gold",
    description: "Interlocking links balance structure and movement for a considered daily signature.",
    price: 11200,
    discountedPrice: 9800,
    category: "bracelets",
    collectionSlug: "timeless-gold",
    featured: false,
    isNew: true,
    details: ["Custom lobster clasp", "Polished finish from our Bengaluru partners"],
  },
  {
    slug: "amrita-baroque-lariat",
    name: "Amrita Pearl Lariat",
    subtitle: "A sliding gold bead for endless neckline configurations",
    description: "A flowing fine gold chain terminating in twin natural baroque pearls.",
    price: 13900,
    discountedPrice: 11800,
    category: "necklaces",
    collectionSlug: "the-pearl-edit",
    featured: true,
    isNew: true,
    details: ["Adjustable silicone-lined slider", "Wear as lariat or open-back drop"],
  },
  {
    slug: "tara-stud-earrings",
    name: "Tara Pebble Studs",
    subtitle: "Small sculptural studs with a liquid silhouette",
    description: "A softly irregular pair of studs shaped to look discovered rather than manufactured.",
    price: 4600,
    category: "earrings",
    collectionSlug: "timeless-gold",
    featured: false,
    isNew: true,
    details: ["Butterfly backs", "Comfortable for daily wear"],
  },
  {
    slug: "soma-moon-pendant",
    name: "Soma Moon Pendant",
    subtitle: "A brushed silver crescent on a fine chain",
    description: "A quiet crescent pendant that layers easily and catches the light at the collarbone.",
    price: 6200,
    category: "pendants",
    collectionSlug: "silver-moon",
    featured: true,
    isNew: false,
    details: ["Satin-brushed finish", "Adjustable chain length"],
  },
  {
    slug: "heritage-emerald-band",
    name: "Heritage Emerald Band",
    subtitle: "A low-profile green stone set in antique gold",
    description: "A considered band with a deep green cabochon and a gently irregular bezel.",
    price: 16400,
    category: "rings",
    collectionSlug: "atelier-heritage",
    featured: true,
    isNew: false,
    details: ["Natural variation in every stone", "Antique satin finish"],
  },
] as const;
